### ISSUE TITLE
How to prevent just anyone joining your server.

### ISSUE THREAD

**Issue by danielwilson654** [mmatczuk/go-http-tunnel#105]
Hello, I have been playing around with this and it seems to be working well and easy to set up, maybe to easy. Then it occurred to me that my server isn't only allowing "known" clients to connect, but just anybody who happens to know the server IP.

How does one restrict what clients are allowed to connect to a server?

Thanks!

**Comment by danielwilson654** [comment]
Found something in the code.
`rootCA := flag.String("rootCA", "", "Path to the trusted certificate chian used for client certificate authentication, if empty any client certificate is accepted")`

Are the server configuration options located anywhere apart from the readme? 

Not sure how to generate a rootCA but I think I have a start now.

**Comment by danielwilson654** [comment]
That's enough for one night I think... Didn't get it going unfortunately.
`sudo ./tunneld -tlsCrt server.crt -tlsKey server.key -rootCA rootCA.key

   ______         __  __________________     __                         __
  / ____/___     / / / /_  __/_  __/ __ \   / /___  ______  ____  ___  / /
 / / __/ __ \   / /_/ / / /   / / / /_/ /  / __/ / / / __ \/ __ \/ _ \/ /
/ /_/ / /_/ /  / __  / / /   / / / ____/  / /_/ /_/ / / / / / / /  __/ /
\____/\____/  /_/ /_/ /_/   /_/ /_/       \__/\__,_/_/ /_/_/ /_/\___/_/
github.com/mmatczuk/go-http-tunnel

failed to create server: listener failed: missing TLSConfig
`

**Comment by danielwilson654** [comment]
Success (finally)! 
This write up shed some light on it. 
https://stuff-things.net/2015/09/17/client-certificate-ca-setup-and-signing/

I also was able to study the container that is still in a PR to get an idea of how the keys are created.

Perhaps don't close this until you consider adding some instructions to the README.md?

**Comment by stobias123** [comment]
@danielwilson654  - this use case is documented in the docs via `-clients` flag or use of `root_ca `

IMO this issue should be closed.

**Comment by danielwilson654** [comment]
Wow.. didn't know the docs existed. I thought the readme was it. Perhaps a link to the docs (https://pkg.go.dev/github.com/mmatczuk/go-http-tunnel) in the readme for noobs like me?
