### ISSUE TITLE
Feature request.  I would like an option for the tunnel to never be cut.  

### ISSUE THREAD

**Issue by synaption** [mmatczuk/go-http-tunnel#129]
If I try to start a tunnel when a tunnel is already using that port on the server, the program exits with error "failed to start tunnels: connection is being cut".  My use case is remote raspberry pies that I never want to lose contact with, so for me the ideal behavior would be to not exit when this error occurs.  There are obviously several ways to go about this.  I could obviously write a service for systemd or use cron, but it would be nice if go-http-tunnel handled this itself.  I might poke around the code and figure it out myself, but I figured I'd ask first and maybe somebody already knows right where to make the change.

**Comment by 1ubuntuuser** [comment]
How did you solve this one?
