### ISSUE TITLE
How to SSH to the client using go-http-tunnel implementation

### ISSUE THREAD

**Issue by LiveEarth** [mmatczuk/go-http-tunnel#130]
Hello team, @mmatczuk  I follow your instruction and create server and client side part of go-http-tunnel (implemented ./tunneld and ./tunnel)
Everything works fine, but don't know how to use ssh tunnel option:

    server_addr: SERVER_IP:5223
    tunnels:
      webui:
        proto: http
        addr: localhost:8080
        auth: user:password
        host: webui.my-tunnel-host.com
      ssh:      <== HOW TO USE THIS OPTION?
        proto: tcp
        addr: 192.168.0.5:22
        remote_addr: 0.0.0.0:22

My question are how to use go-http-tunnel to SSH to the client?

Best regards, be healthy

**Comment by LiveEarth** [comment]
No answer from developer

**Comment by marcusfollrud** [comment]
change remote_addr to something like 0.0.0.0:2222 in your client config. This will bind port 2222 on the server. After that you connect to ssh like you normally do

`$ ssh user@127.0.0.1 -p 2222`

So if you have a lot of connections make sure you have free ports available on the server
