### ISSUE TITLE
ssh tunnel connection timeout 

### ISSUE THREAD

**Issue by dipenpatel235** [mmatczuk/go-http-tunnel#132]
@mmatczuk 
I want to ssh on `system(172.16.209.145)` from `client` using this tunnel solution tool. 
so i am not able to do that. 
getting timeout error.(attached screenshot of that)
added my architecture diagram screenshot and also i have added my `tunnel.yml` file content in that screenshot

i am trying to execute below command from `client`
```
ssh -p 2222 ubuntu@192.168.0.25
```

let me know what things are wrong so i can fix it.

![tunnel_diagram (1)](https://user-images.githubusercontent.com/8135097/119991300-f04ea000-bfe6-11eb-99f4-9e6822ae51b4.jpg)
![image](https://user-images.githubusercontent.com/8135097/119991450-1411e600-bfe7-11eb-9228-aef5ba7fb0ae.png)

Thanks

**Comment by hons82** [comment]
Why 2222? Do u have that port open somewhere?

**Comment by dipenpatel235** [comment]
@hons82 2222 post because if i used 22 then its saying to me already in used.

**Comment by hons82** [comment]
From the message it looks like the port 2222 is not opened on that machine

**Comment by dipenpatel235** [comment]
@hons82 can u tell me in which server i need to keep open that port (client, server ,or system as per above architecture diagram)?

**Comment by hons82** [comment]
Wait a sec. I think there is something wrong in this constellation.

- tunneld needs to run on a machine that is public available 
- tunnel needs to run on a private machine, so a machine that you want to access from everywhere, but it is tecnically hidden by let's say a firewall

Now you can access the machine where tunnel is running from outside by calling `ssh <ip_of_tuinneld>`. 

Speaking in the words of your diagram you should be able to call `ssh -p 2222 ubuntu@192.168.0.25` on the machine called system to access the client, but not viceversa.

**Comment by dipenpatel235** [comment]
@hons82 i got your point and founded my mistake. so let me try it as per given by you and update you once testing done .

Thanks for your valuable time.

**Comment by dipenpatel235** [comment]
@hons82 its working fine.
thanks you so much for your help.
