### ISSUE TITLE
Protocol Proxy Error

### ISSUE THREAD

**Issue by pyaethetponphyo** [mmatczuk/go-http-tunnel#138]
Hi all,
i'm having this issue after running tunneld for some time. Could you please kindly help how can i fix this issue?

Nov 24 22:50:58 hoppin tunneld[81783]: 2021/11/25 05:20:58 level 0 msg proxy error identifier T22YTAZ-UMLE7ZH-XJV2Q6O-RPCRNXY-S3WJA6O-6GI4F5F-XJ67GSO-W4J4DQ5 ctrlMsg &{proxy [::]:5055 tcp } err io error: Put https://T22YTAZ-UMLE7ZH-XJV2Q6O-RPCRNXY-S3WJA6O-6GI4F5F-XJ67GSO-W4J4DQ5: stream error: stream ID 6089; PROTOCOL_ERROR
Nov 24 22:51:03 hoppin tunneld[81783]: 2021/11/25 05:21:03 level 0 msg proxy error identifier T22YTAZ-UMLE7ZH-XJV2Q6O-RPCRNXY-S3WJA6O-6GI4F5F-XJ67GSO-W4J4DQ5 ctrlMsg &{proxy [::]:5055 tcp } err io error: Put https://T22YTAZ-UMLE7ZH-XJV2Q6O-RPCRNXY-S3WJA6O-6GI4F5F-XJ67GSO-W4J4DQ5: stream error: stream ID 6091; PROTOCOL_ERROR
Nov 24 22:51:09 hoppin tunneld[81783]: 2021/11/25 05:21:09 level 0 msg proxy error identifier T22YTAZ-UMLE7ZH-XJV2Q6O-RPCRNXY-S3WJA6O-6GI4F5F-XJ67GSO-W4J4DQ5 ctrlMsg &{proxy [::]:5055 tcp } err io error: Put https^C

**Comment by 1ubuntuuser** [comment]
How did you solve this one?

**Comment by nickpick42** [comment]
Running into same error. Any solutions?
