### ISSUE TITLE
How do i start my server but subscribe later?

### ISSUE THREAD

**Issue by pault84** [mmatczuk/go-http-tunnel#20]
Basically, i want to run 1 proxy and n clients.
But I am unaware of the clients at start-up.

Can I start the server in a goroutine and call subscribe on that server at a later time?

**Comment by mmatczuk** [comment]
Hi Paul,
the server supports this even with unsubscribing connected clients etc. yet the CLI does not. You can use the tunnel as a library and register clients yourself see https://github.com/mmatczuk/go-http-tunnel/blob/master/cmd/tunneld/tunneld.go for reference how this can be done. 

I'll add another issue to add control over that while running. Maybe a REST API on a dedicated port WDYT would be the most convenient to use for you?

**Comment by pault84** [comment]
Right now i've solved it by adding a for {} to my main loop and running Server.Start() in a go func.
Either way a rest-api to add new clients would be great 👍

**Comment by mmatczuk** [comment]
@pault84 I moved the REST API to https://github.com/mmatczuk/go-http-tunnel/issues/21. If you value the tunnel please consider starring it to help the adoption, thanks!
