### ISSUE TITLE
Server cli add possibility to manage subscriptions in runtime 

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/go-http-tunnel#21]
Server CLI should start a separate HTTP listener and provide a REST api to inspect and manage subscriptions.

**Comment by codeskyblue** [comment]
How about 

```go
server.OnSubscribe = func(client SomeType) bool {
    return true
}
```

**Comment by mmatczuk** [comment]
@codeskyblue it's too simplistic, the library actually supports all this inducing client forced disconnects but it's not exposed in the API.
