### ISSUE TITLE
URL based client communication

### ISSUE THREAD

**Issue by pault84** [mmatczuk/go-http-tunnel#22]
Is it currently possible to subscribe a particular client to url path?

Let's say i have 2 clients and 1 server.

client 1 should be responsible for responses to server:80/client1/query
client 2 should be responsible for responses to server:80/client2/query

Is this doable? 

i tried changing the client tunnel endpoint to a path based on their "id"  but that didn't work.

**Comment by mmatczuk** [comment]
Hi @pault84,
I'd recommend using host so that you would have `client1.server/query` and `client2.server/query` this is simpler and more error prone. In general case striping URL path should be avoided see https://github.com/fabiolb/fabio/issues/2.

**Comment by pault84** [comment]
that would only work if host is an actual DNS name right? that would not work for IP's

**Comment by mmatczuk** [comment]
Yep, you can use `/etc/hosts` for development and if you have like two or three clients you can also get some free DNS no problem.
