### ISSUE TITLE
Add build documentation / Future release

### ISSUE THREAD

**Issue by CasperCLD** [mmatczuk/go-http-tunnel#29]
First off: awesome project. Really cool to see an open-source alternative to ngrok.

I'm running into #26 on MacOS, which can be solved by building from `master`.
Since the build process is not documented and I'm not that familiar with Go, I cannot build the app myself.

This issue is really blocking, because I cannot use the application.
When will there be a new release so I can use it?

Cheers.

EDIT:  I added the fake `ssh` config from the README.md to make it work.

**Comment by mmatczuk** [comment]
Hi @CasperCLD,
please checkout the new release https://github.com/mmatczuk/go-http-tunnel/releases/tag/v.1.1

**Comment by CasperCLD** [comment]
Awesome, thank you very much !

**Comment by mmatczuk** [comment]
no problem

**Comment by mmatczuk** [comment]
@CasperCLD if you like it you may conciser staring the project
