### ISSUE TITLE
No display on the website (public url)

### ISSUE THREAD

**Issue by arghyakusumdas7** [mmatczuk/go-http-tunnel#32]
I am having the following error message on the client side when trying to access the local app from public on a browser. 

proxy HTTP level 0 msg failed to read request ctrlMsg &{proxy http .... <hostname:port>} err EOF

[It is a bokeh app. The app is receiving the traffics but I am not getting any display in the website]

**Comment by mmatczuk** [comment]
Something has cut the connection when server was writing to client. Hard to say what it could be based on the description.
