### ISSUE TITLE
HTTP Proxy Error on some HTTPS endpoints

### ISSUE THREAD

**Issue by jonreeves** [mmatczuk/go-http-tunnel#33]
I'm unable to get access to a machine running PFSense over HTTPS. I get the following error in the Tunnel Client:
```
http: proxy error: x509: certificate signed by unknown authority
```

The odd thing is I have a NAS on the same network that uses HTTPS too and that one I'm able to reach just fine. Both have self-signed certificates, so I expect to get the Warning in the browser, but after proceeding beyond that warning, the PFSense one fails with a HTTP 502 error and I get that message in the Tunnel Client. The NAS one is just fine.

Any ideas? I already have `insecure_skip_verify: true` in the client config.

**Comment by mmatczuk** [comment]
Hi @jonreeves `insecure_skip_verify: true` is for the tunnel client server communication not for the proxying. I confirm that it would not work with self signed certificates. Can you use simple HTTP? If not maybe you can get https://letsencrypt.org certificate?

**Comment by mmatczuk** [comment]
The best option would be to provide a proper handling on this by a separate tls tunnel type.

**Comment by jonreeves** [comment]
ah ok, I just wanted to confirm I wasn't missing something. I can probably get the Root CA certs installed onto the machine where I run the server and it should work then. Thanks for the clarification. Great tool by the way.
