### ISSUE TITLE
Linux/mips binary

### ISSUE THREAD

**Issue by bluemeda** [mmatczuk/go-http-tunnel#39]
please provide linux/mips (32bit) binary

**Comment by bluemeda** [comment]
Solved, finally I can compile it by myself
just go to `cmd/tunnel`
get the dependencies
`go get -u gopkg.in/yaml.v2`
`go get -u github.com/cenkalti/backoff`
then compile it
`GOOS=linux GOARCH=mips go build`

**Comment by bluemeda** [comment]
I just compiled it successfully, but when I executed it in LEDE(openWRT) it said `Illegal instruction`

**Comment by mmatczuk** [comment]
1. `export CGO_ENABLED=0`
1. Get to know if it's mips or mipsle (32-bit MIPS big- and little-endian)

**Comment by bluemeda** [comment]
this is my cpuinfo
```
system type		: bcm63xx/HW553 (0x6358/0xA1)
machine			: Huawei EchoLife HG553
processor		: 0
cpu model		: Broadcom BMIPS4350 V1.0
BogoMIPS		: 297.98
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: no
isa			: mips1 mips2 mips32r1
ASEs implemented	:
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available
```

I think it doesn't not support **FPU**. So, any go-based code can't be executed.

**Comment by mmatczuk** [comment]
It seems there are two options

1. recompile kernel to enable softfloat
1. use 1.8.3 with a patch from https://github.com/golang/go/issues/18162 https://gist.github.com/ematsu/0410ef110e1e9ad9733b9f8dccfe729b/archive/73f8f580bb6fb07c1d12bf60008df9c66c9d0e46.zip

Good luck!

**Comment by RoganDawes** [comment]
This is my command line for compiling the client for my OpenWrt router (MT7621), using go1.14.9:
```
GOMIPS=softfloat GOOS=linux GOARCH=mipsle go build -ldflags="-s -w"
```
