### ISSUE TITLE
How to migrate from koding/tunnel to mmatczuk/tunnel?

### ISSUE THREAD

**Issue by hugows** [mmatczuk/go-http-tunnel#4]
This is just an idea of course, but it would be very interesting to provide a "migration path" for people that use koding/tunnel and want to *try* this project.  

(Ideally one would just change the import, much like SQL adapters... But of course the API might not be exactly compatible)

**Comment by mmatczuk** [comment]
@hugows I'm porting proxy functions when it's done there will be a cli added so that using this will be really simple.

**Comment by mmatczuk** [comment]
Hi @hugows I have just released tunnel v1.0. This release contains a cli that I hope will simplify setting up tunnels a lot. It also allows you to set basic auth in configuration. Enjoy. If you have any troubles, doubts or suggestions let me know.
