### ISSUE TITLE
how to expose myself(or say localhost) to the internet world without localtunnel and any framework?

### ISSUE THREAD

**Issue by anlexN** [mmatczuk/go-http-tunnel#42]
- I 'm home, my home ip is dynamic. please help me.

**Comment by keyoti** [comment]
What you're looking for is port forwarding which you setup in your home router.  You can also use DNS service like afraid.org to give yourself a host name.

**Comment by mmatczuk** [comment]
@anlexN your router IP is probably fixed (or does not change too often), if you can run `tunneld` on your router then you could run `tunnel` on your laptop, connect to the router and do the tunneling. If you cannot access your router you can always use a remote server, any other host that is publicly available.

**Comment by anlexN** [comment]
@mmatczuk , i think you are right. my ip does not change too often. average, once at a day.
I always access my router through **192.168.199.1** , but now, you say  
> you can run tunneld on your router. 
 how can i access my router through windows command?
can you tell me details? please
