### ISSUE TITLE
client: max_time never set to 0

### ISSUE THREAD

**Issue by helinwang** [mmatczuk/go-http-tunnel#46]
Hi, thanks for the repo!

I am using `v1.1` release. This is what I set in the `tunnel.xml`:
```
  interval: 100ms
  multiplier: 1
  max_interval: 100ms
  max_time: 0
```

This is what the program prints:
```
  interval: 100ms
  multiplier: 1
  max_interval: 100ms
  max_time: 15m0s
```

I have to workaround it with:
```
  interval: 100ms
  multiplier: 1
  max_interval: 100ms
  max_time: 999999h
```

Wonder how to set the max time to 0?

**Comment by mmatczuk** [comment]
Did you try `0s`?

**Comment by mmatczuk** [comment]
@helinwang check the new release.

**Comment by helinwang** [comment]
Thank you!
