### ISSUE TITLE
Identify dead connections

### ISSUE THREAD

**Issue by goriccardo** [mmatczuk/go-http-tunnel#49]
I'm having issues with long lived connections:
- the server sometimes receives connection requests from clients that are reportedly already connected, and reject them.
- when the server restarts, some clients do not try to connect again.

I debugged the issue and found out that once the client is connected to the server this connection is kept open waiting for a user to connect to the server. If the connection dies without notifying the client or server, they would keep listening to dead connections.

If the server believes that a dead connection belonging to an id is open it would reject new (valid) connections from that id.

A client may keep listening to a dead connection forever, effectively preventing the client to retry and open a fresh connection.

My workaround was to turn on TCP keepalive for the client connection, and to let the server ping (http ping) the existing client connection when a connection request with an already connected id is received.

**Comment by mmatczuk** [comment]
For ping I assume you mean https://godoc.org/golang.org/x/net/http2#ClientConn.Ping.

This seems perfectly valid, could you please send a PR.

**Comment by goriccardo** [comment]
Yes that ping :)

I'll prepare a PR tonight, I have to cleanup my workaround a bit.


Il 20 Nov 2017 15:42, "Michał Matczuk" <notifications@github.com> ha
scritto:

For ping I assume you mean https://godoc.org/golang.org/
x/net/http2#ClientConn.Ping.

This seems perfectly valid, could you please send a PR.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mmatczuk/go-http-tunnel/issues/49#issuecomment-345715247>,
or mute the thread

**Comment by mmatczuk** [comment]
Thanks.

**Comment by mmatczuk** [comment]
Do you have an environment where you could easily reproduce the issue?

**Comment by goriccardo** [comment]
The only way I found to test the issue was using iptables to close drop packets to/from the server and kill either the client or the server.

Unfortunately I did not find an easy way to reproduce the bug without using network filtering techniques.

**Comment by mmatczuk** [comment]
Ok that's fine. I have slightly different implementation idea. Will get back to you shortly.

**Comment by mmatczuk** [comment]
@goriccardo could you check if https://github.com/mmatczuk/go-http-tunnel/pull/52 works for you?

**Comment by goriccardo** [comment]
I will test it later today, thanks.

On a side note I was not confident in using the tcpkeepalive package
because apparently there are some known issues reported on its readme. I
did not look at them closely though.

**Comment by mmatczuk** [comment]
The conclusion is to use `SetKeepAlive` that shall be safe see https://github.com/felixge/tcpkeepalive/issues/3.

**Comment by goriccardo** [comment]
#52 seems to work fine, thanks.

**Comment by mmatczuk** [comment]
Thanks!

**Comment by mmatczuk** [comment]
Fixed by #52.
