### ISSUE TITLE
io error on http2

### ISSUE THREAD

**Issue by radutopala** [mmatczuk/go-http-tunnel#53]
I get this error: `io error: Put http://localhost/login: http2: unsupported scheme` .. what could be the problem?

**Comment by mmatczuk** [comment]
`http2://` in config file?

**Comment by radutopala** [comment]
I was accessing `http://localhost` in browser. If I access `http://localhost/login` it works fine .. I think the underlying app (PHP Symfony app) I'm accessing does not support http2.. still investigating.

**Comment by mmatczuk** [comment]
Does it work with http://localhost/ (note the slash)

You need to provide some more context anyway.

**Comment by radutopala** [comment]
@mmatczuk I use an apache without http2 support, could that be the cause?

**Comment by mmatczuk** [comment]
No, the error is that you try to call "http" instead of "https" the question is where.

**Comment by radutopala** [comment]
Was reading this .. https://stackoverflow.com/questions/34468231/how-do-i-make-a-http2-only-request-over-http-in-go .. so do we need to use only https with the tunnel?

**Comment by mmatczuk** [comment]
No, `tuneld -httpAddr :8080 -httpsAddr ""` you can start server with both http and https send proper messages to proper ports.

**Comment by radutopala** [comment]
I did start the server with `tunneld -httpAddr :80 -httpsAddr ""` and the same error appears in browser, but only when a redirect is happening from within the app..

**Comment by mmatczuk** [comment]
Probably the location is wrong. Could you share some more details.

**Comment by radutopala** [comment]
@mmatczuk I can't really publicly share all the config.. but I'm happy to have a Skype or Hangouts share screen if you can..

**Comment by mmatczuk** [comment]
Drop me an email then.

**Comment by radutopala** [comment]
Pls check https://github.com/golang/net/blob/master/http2/transport.go#L348..

**Comment by radutopala** [comment]
@mmatczuk have sent you an email at michal@scylladb.com.

**Comment by radutopala** [comment]
@mmatczuk on my end it's pretty clear that if the app sends a redirect, this redirect is not valid in http2 for some reason..

**Comment by radutopala** [comment]
@mmatczuk so.. does it makes any sense? 😄

**Comment by radutopala** [comment]
@mmatczuk is there a way to fix this?

**Comment by mmatczuk** [comment]
PRs are welcome.

**Comment by mmatczuk** [comment]
@radutopala thanks for reporting, can you try https://github.com/mmatczuk/go-http-tunnel/pull/55.

**Comment by radutopala** [comment]
@mmatczuk I can confirm this is fixed on #55.

**Comment by mmatczuk** [comment]
Fied by #55
