### ISSUE TITLE
Add configuration for server listening ports

### ISSUE THREAD

**Issue by andrewwippler** [mmatczuk/go-http-tunnel#68]
It would be nice to have an option to specify alternate ports that the server listens on for http and https requests.

**Comment by mmatczuk** [comment]
You do that by specifying host:port, https://github.com/mmatczuk/go-http-tunnel/blob/master/cmd/tunneld/options.go#L52

**Comment by andrewwippler** [comment]
Wow, that was a quick fix :)

Newer to Go and did not get to that point in the source before creating an issue. Glad to have that option available.
