### ISSUE TITLE
TCP connection security

### ISSUE THREAD

**Issue by riyaz-ali** [mmatczuk/go-http-tunnel#70]
Hey there!! thanks for the great tool!! I am really loving it😃😃
My question is, is the connection between the tunnel client and the tunnel server secured (encrypted) and if yes then how? I mean using which certificates and key? and if the server uses the self-signed certificate for the purpose, is it possible that someone could MITM my connection?

**Comment by mmatczuk** [comment]
Yes it's TLS encrypted and can be controller, for details consult command parameters.
