### ISSUE TITLE
binary Release for 32 bit

### ISSUE THREAD

**Issue by surereddy** [mmatczuk/go-http-tunnel#73]
Hello sir can you please give me release for 32 bit ubuntu .whe i try to make it have errors 

go-http-tunnel# make
cannot find package "_/root/go-http-tunnel" in any of:
	/root/go/src/_/root/go-http-tunnel (from $GOROOT)
	/root/goworkspace/src/_/root/go-http-tunnel (from $GOPATH)
cannot find package "_/root/go-http-tunnel/cmd/tunnel" in any of:
	/root/go/src/_/root/go-http-tunnel/cmd/tunnel (from $GOROOT)
	/root/goworkspace/src/_/root/go-http-tunnel/cmd/tunnel (from $GOPATH)
cannot find package "_/root/go-http-tunnel/cmd/tunneld" in any of:
	/root/go/src/_/root/go-http-tunnel/cmd/tunneld (from $GOROOT)
	/root/goworkspace/src/_/root/go-http-tunnel/cmd/tunneld (from $GOPATH)
cannot find package "_/root/go-http-tunnel/id" in any of:
	/root/go/src/_/root/go-http-tunnel/id (from $GOROOT)
	/root/goworkspace/src/_/root/go-http-tunnel/id (from $GOPATH)
cannot find package "_/root/go-http-tunnel/log" in any of:
	/root/go/src/_/root/go-http-tunnel/log (from $GOROOT)
	/root/goworkspace/src/_/root/go-http-tunnel/log (from $GOPATH)
cannot find package "_/root/go-http-tunnel/proto" in any of:
	/root/go/src/_/root/go-http-tunnel/proto (from $GOROOT)
	/root/goworkspace/src/_/root/go-http-tunnel/proto (from $GOPATH)
cannot find package "_/root/go-http-tunnel/tunnelmock" in any of:
	/root/go/src/_/root/go-http-tunnel/tunnelmock (from $GOROOT)
	/root/goworkspace/src/_/root/go-http-tunnel/tunnelmock (from $GOPATH)
make: ineffassign: Command not found
make: *** [.check-ineffassign] Error 127

**Comment by mmatczuk** [comment]
@surereddy did you try https://github.com/mmatczuk/go-http-tunnel/releases/download/2.1/tunnel_linux_386.tar.gz ?
