### ISSUE TITLE
SSL oddness

### ISSUE THREAD

**Issue by komcrad** [mmatczuk/go-http-tunnel#75]
I have a custom embedded device running the tunnel client with the following config:

server_addr: SERVER_IP:5223
tunnels:
    webui:
      proto: http
      addr: https://localhost:10001
      host: MY_DOMAIN

When I run it and try to hit MY_DOMAIN, the tunnel client logs spit out
"http: proxy error: x509: failed to load system roots and no roots provided"

any ideas?

**Comment by mmatczuk** [comment]
Make sure you have certificates installed https://github.com/golang/go/commit/ce645534e481368b4ec6141d48eb361422e423b8
