### ISSUE TITLE
SSH Tunneling 

### ISSUE THREAD

**Issue by rohinrohin** [mmatczuk/go-http-tunnel#77]
Can this library work with TCP forwarding for SSH similar to ngrok. I was unable to find any documentation regarding this.

**Comment by mmatczuk** [comment]
Yes it can, you will find example in readme and in the command help.

**Comment by LiveEarth** [comment]
Hi @mmatczuk I can not found tutorial on that how to ssh on the client? I made every step and connect server and client, but don't know how to ssh on the client.
Best regards
