### ISSUE TITLE
Possible throttle from ISP

### ISSUE THREAD

**Issue by ltotsas** [mmatczuk/go-http-tunnel#80]
Currently, i have setup a reverse tunnel through AWS but i am getting really low upload/download speeds. No more than 400kbps when my network speed when my network speed is around 80Mbps.
i moved my server in another network to test if the problem is from actually from localhost, AWS or from go-http-tunnel, but that's not the case. 

The only thing that is left is that my ISP limits my connection, apart from blocking all ports. Is there any solution for that through go-http-tunnel?

**Comment by aterebenkov** [comment]
have same problem with tcp tunnel for rtsp, 400kbps max bitrate :( 
Does anyone know how to fix this?
